platform :ios, ‘8.0’
target ‘XACASampleDemo’ do
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SDWebImage', '~> 3.7.6'
pod 'MJRefresh', '~> 3.1.12'
pod 'ReactiveCocoa', '~> 2.5'
pod 'QMUIKit', '~> 1.4.0'
end
